runtime: custom
service: predict-mobilenet
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 6
  disk_size_gb: 10
